# B社の事例

## 与件文

　B社は資本金500万円、従業者数は２ 代目社長を含めて８ 名（うちパート３名）で、スポーツ用品の加工・販売を行っている。現在の事業所は、小売１店舗（ユニフォームなどの加工、刺しゅうを行う作業場併設）である。取扱商品は野球、サッカー、バスケットボールやバレーボールなどの球技用品、陸上用品、各種ユニフォーム、ジャージーなどのトレーニング用品、テーピングやサポーターなどのスポーツ関連用品などである。また、近隣の公立小中学校の体操服や運動靴も扱っている。

　B社はX県の都市部近郊に立地する。付近にはJRと大手私鉄が乗り入れている駅があり、交通の便がよいため、住宅街が広がり、戸建てやアパート、マンションなどから構成されている。駅前は商店が多く、スーパーを中心に各種専門店や飲食店などがあり、買い物も便利でにぎわっている。

　また、B社のある町の中には幹線道路が通っていて、自動車での移動も便利である。すぐ近くには大きな河川があり、河川敷がスポーツ施設として整備され、野球場、サッカー場、多目的広場などがある。近隣の強豪社会人野球チームがここを借りて練習しているということで地域住民の野球熱が高く、野球場の数も通常の河川敷に比べるとかなり多い。

　B社は1955年にこの地で衣料品店として、初代社長である、現社長の父が開業した。1960年代から付近の宅地開発が始まり、居住者が急激に増えた。同時に子どもの数も増えてきたため、公立小中学校が新たに開校し、公立小中学校の体操服や運動靴を納品する業者として指定を受けた。この際、体操服に校章をプリントしたり、刺しゅうでネームを入れたりする加工技術を初代社長が身に付けて、この技術が２ 代目社長にも継承されている。

　子どもの数が増えてきたことと、河川敷に野球場が整備されたこと、さらにはプロ野球の人気が高まってきたことなどがあり、1970年代初頭から少年野球チームがこの地域で相次いで設立された。初代社長の知り合いも少年野球チームを設立し、B社はユニフォームや野球用品の注文について相談を受けた。ユニフォームについては衣料品の仕入れルートから紹介を受けて調達し、自店舗の作業場でチーム名や背番号の切り文字の切り抜き、貼り付け加工をすることができた。また、ユニフォームの調達を通じて野球用品の調達ルートも確保できた。1970年代初頭、まだ付近にはスポーツ用品を扱う店舗がなかったため、複数の少年野球チームから野球用品の調達について問い合わせを受けるようになり、ちょうど事業を承継した２ 代目社長はビジネスチャンスを感じ、思い切って衣料品店をスポーツ用品店に事業転換することとした。

　1970年代から1980年代までは少年野球が大変盛んであり、子どもの数も多く、毎年多くの小学生が各少年野球チームに加入したため、４月と５月には新規のユニフォームや野球用品の注文が殺到した。

　低学年から野球を始めた子どもは、成長に伴って何度か、ユニフォーム、バット、グラブ、スパイクといった野球用品を買い替えることになる。B社は各少年野球チームから指定業者となっていたので、こうした買い替え需要を取り込むことに成功しており、また、チームを通さなくても個別に買い物に来る顧客を囲い込んでいた。さらに、年間を通じて、各チームに対してボール、スコア表、グラウンドマーカー（ラインを引く白い粉）などの納入もあった。

　1990年代初頭にはJリーグが開幕し、河川敷にサッカー場も整備され、今度は急激に少年サッカーチームが増えたため、B社はサッカー用品の品揃えも充実させ、各少年サッカーチームとも取引を行うように事業の幅を広げていった。

　子どもたちのスポーツ活動が多様化してきたので、バスケットボールやバレーボールなどの球技用品、陸上用品などの扱いにも着手し、中学校の部活動にも対応できるように取扱商品を増やしていった。

　しかし、2000年代に入ると、付近にサッカーやバスケットボール用品の専門店が相次いで開業し、過当競争になった。これらの専門店と比べると、B社は品揃えの点で見劣りがしている。また、数年前には自動車で15分ほどの場所に、大型駐車場を備えてチェーン展開をしている大型スポーツ用品量販店が出店した。その量販店では、かなり低価格で販売されているため、B社は価格面で太刀打ちができない。

　そこでB社は、品揃えと提案力に自信のある野球用品をより専門的に取り扱っていくこととした。

　古くから取引がある各少年野球チームは、B社の各種有名スポーツブランド用品の取り揃え、ユニフォーム加工技術や納品の確かさ、オリジナルバッグなどのオリジナル用品への対応力、子どもたちの体格や技術に応じた野球用品の提案力などについて高く評価しており、チームのメンバーや保護者には、引き続きB社からの購入を薦めてくれている。

　ユニフォームやオリジナル用品などは、各チームに一括納品できる。しかし、メンバーの保護者から、価格面でのメリットなどを理由に、大型スポーツ用品量販店で汎用品の個別購入を希望された場合、各チームの監督ともB社で購入することをなかなか強く言えなくなっている。

　また、成長に伴う買い替えや、より良い用品への買い替えも保護者には金銭的な負担となっていて、他の習い事もあり、買い替えの負担を理由に野球をやめてしまう子どもたちもいるということでB社は相談を受けていた。

　さらに、野球をやりたいという子どもの確保も各チームの課題となっている。従来のようにポスターを貼ったりチラシを配布したりするといった募集活動に加え、SNSを用いた募集活動への対応がある。また、女子の軟式野球が盛んになってはいるものの、まだまだ少ない女子の参加希望者を増やしていくことも課題である。どのチームも女子のメンバー獲得に苦しんでいる。

　他には、チームやそのメンバーのさまざまなデータ管理についても、たとえばスマートフォンを使って何かできないかとB社は相談を受けていた。

　２代目社長は、ICT企業に勤めている30代の長男がB社を事業承継する決意をして戻ってくるのを機に、次のような事業内容の見直しをすることとした。

　第１ に、総合的なスポーツ用品を扱いながらも、1970年代に事業転換したときからの強みである、野球用品の強化をさらに進める。特に子どもたち一人一人の体格や技術、特性に応じた商品カスタマイズの提案力をより強化することで、大型スポーツ用品量販店との差別化を図る。

　第２ に、各少年野球チームの監督とのより密接なコミュニケーションを図り、各チームのデータ管理、メンバーや保護者の要望の情報把握、および相談を受けた際のアドバイスへの対応を進める。また、用品に関する買い替えなどの多様なニーズに応えるいくつかの販売方法を導入する。

　第３に、女子の軟式野球が盛んになってきたことに着目し、女子メンバー獲得に苦しんでいるチームを支援し、女子向けの野球用品の提案力を高め、新規顧客としての女子チームの開拓を行う。

　第４に、インターネットの活用の見直しである。現在は店舗紹介のホームページを設けている程度である。今後、このホームページにどのような情報や機能を搭載すべきか、また、SNSやスマートフォンアプリの活用方法についても検討し、顧客との関係性強化を考えている。

　B社社長は、自社の強みを生かせる新たな事業展開ができるよう、中小企業診断士に助言を求めた。

（令和5年度　中小企業診断士2次筆記試験　事例2　問題より引用）

## 問題

### 第1問（配点30点）

#### 問題文

B社の現状について、3C（Customer：顧客、Competitor：競合、Company：自社）分析の観点から150字以内で述べよ。

#### ロジック

##### 現状分析

[plantuml]
----
@startmindmap

@endmindmap
----

##### 課題設定

[plantuml]
----
@startmindmap

@endmindmap
----

##### 解決策

[plantuml]
----
@startmindmap

@endmindmap
----
#### 解答


### 第2問（配点20点）

#### 問題文

低学年から野球を始めた子どもは、成長やより良い用品への願望によって、ユニフォーム、バット、グラブ、スパイクといった野球用品を何度か買い替えることになるため、金銭的負担を減らしたいという保護者のニーズが存在する。 B社は、こうしたニーズにどのような販売方法で対応すべきか、プライシングの新しい流れを考慮して、100字以内で助言せよ（ただし、割賦販売による取得は除く）。

#### ロジック

##### 現状分析

[plantuml]
----
@startmindmap

@endmindmap
----

##### 課題設定

[plantuml]
----
@startmindmap

@endmindmap
----

##### 解決策

[plantuml]
----
@startmindmap

@endmindmap
----

#### 解答


### 第3問（配点20点）


#### 問題文

女子の軟式野球チームはメンバーの獲得に苦しんでいる。B社はメンバーの増員のために協力することになった。そのためにB社が取るべきプロモーションやイベントについて、100字以内で助言せよ

#### ロジック

##### 現状分析

[plantuml]
----
@startmindmap

@endmindmap
----

##### 課題設定

[plantuml]
----
@startmindmap

@endmindmap
----

##### 解決策

[plantuml]
----
@startmindmap

@endmindmap
----

#### 解答

### 第4問（配点30点）

#### 問題文

B社社長は、長期的な売上げを高めるために、ホームページ、SNS、スマートフォンアプリの開発などによるオンライン・コミュニケーションを活用し、関係性の強化を図ろうと考えている。誰にどのような対応をとるべきか、150字以内で助言せよ。

#### ロジック

##### 現状分析

[plantuml]
----
@startmindmap

@endmindmap
----

##### 課題設定

[plantuml]
----
@startmindmap

@endmindmap
----

##### 解決策

[plantuml]
----
@startmindmap

@endmindmap
----

#### 解答

