# Ａ社の事例

## 与件文

　A社は、資本金１ 千万円、従業員15名（正社員５ 名、アルバイト10名）の蕎麦店である。先代経営者は地方から上京し、都市部の老舗蕎麦店で修業し、1960年代後半にのれん分けして大都市近郊に分店として開業した。鉄道の最寄り駅からバスで20分ほど離れた県道沿いに立地し、当時はまだ農地の中に住宅が点在する閑散とした中での開業であった。

　開業当初は小さな店舗を持ちながらも、蕎麦を自前で打っており、コシの強い蕎麦が人気を博した。出前中心の営業を展開し、地域住民を取り込むことで、リピート客を増やしていった。また、高度経済成長によって自家用車が普及する途上にあったことから、多少離れていてもマイカーで来店する顧客も年々増え始め、県道沿いの立地が功を奏した。付近には飲食店がほとんどなかったことから、地元で数少ない飲食店の一つとして顧客のニーズに応えるようになり、蕎麦店の範疇を超えるようになった。うどん、丼もの、カレー、ウナギ、豚カツ、オムライスなどもメニューに加え始め、まちの食堂的な役割を担うようになっていった。

　1980年代には、店舗周辺の宅地化が急速に進み、地域人口が増えるに従って、来店客、出前の件数ともに増加していった。1980年代末には売上高が１ 億円に達するようになった。客数の増加に伴い店舗規模を拡大し、駐車場の規模も拡大した。店舗の建て替えによって、収容客数は30席から80席にまで拡大し、厨房設備も拡張し、出前を担当する従業員の数もアルバイトを含めて20名にまで増加した。

　しかしながら、1990年代半ばになると、近隣にファミリーレストランやうどんやラーメンなどのチェーン店、コンビニエンスストアなどの競合が多数現れるようになり、売上高の大半を占める昼食の顧客需要が奪われるようになった。バブル経済崩壊とも重なって、売上高が前年を下回るようになっていった。厨房を担当していた数名の正社員も独立するようになり、重要な役割を担う正社員の離職も相次いだため、一時的に従業員は家族とアルバイトだけとなり、サービスの質の低下を招いていった。

　現経営者は先代の長男であり、先代による事業が低迷していた2000年代初頭に入社した。売上高が５千万円にまで低下していたことから、売上高拡大のためのさまざまな施策を行ってきた。2008年にかけて、メニューの変更を度々行い、先代が行っていた総花的なメニューを見直し、この店にとってはオペレーション効率の悪い丼もの、うどんなどのメニューを廃止し、出前をやめて来店のみの経営とし、元々の看板であった蕎麦に資源を集中した。

　2005年までに売上高は７千万円にまで改善され設備更新の借り入れも完済したが、他方で従業員の業務負荷が高まり、その結果、離職率が高くなった。常に新規募集してアルバイトを採用しても、とりわけ宴会への対応においては仕事の負担が大きく、疲弊して辞めていく従業員が相次いだ。また、新規のメニューの開発力も弱く、効率重視で、接客サービスが粗雑なことが課題であった。

　2010年に先代が経営から離れ、現経営者に引き継がれると、経営方針を見直して、メインの客層を地元のファミリー層に絞り込んだ。店舗の改装を行い、席数を80から50へと変更し、個室やボックス席を中心としたことで家族や友人など複数で来店する顧客が増加した。使用する原材料も厳選して、以前よりも価格を引き上げた。また、看板となるオリジナルメニューを開発し、近隣の競合する外食店とは異なる、商品とサービスの質を高めることで、差別化を行った。ただ、近隣の原材料の仕入れ業者の高齢化によって、原材料の仕入れが不安定になり、新たな供給先の確保が必要となりつつある。

　社内に関しては、正社員を増やして育成を行い、仕事を任せていった。経営者の下に接客、厨房、管理の３部体制とし、それぞれに専業できるリーダーを配置してアルバイトを統括させた。接客リーダーは、全体を統括する役割を担い、A社経営者からの信任も厚く、将来は自分の店を持ちたいと思っていた。他方で、先代経営者の下で働いていたベテランの厨房責任者が厨房リーダーを務め、厨房担当の若手従業員を育成する役割を果たした。管理リーダーは、A社の経営者の妻が務め、会社の財務関係全般、計数管理を行い、給与や売上高の計算などを担った。A社経営者は、接客リーダーとともに会社として目指す方向性を明確にし、目的意識の共有や意思の統一を図るチームづくりを行った。その結果、チームとして相互に助け合う土壌が生まれ、従業員が定着するようになった。とりわけ接客においては、自主的に問題点を提起し解決するような風土が醸成されていた。現経営者に引き継がれてから５ 年間は前年度の売上高を上回るようになり、2015年以降、安定的に利益を確保できる体制となった。

　コロナ禍においては、営業自粛期間に開発した持ち帰り用の半調理製品の販売などでしのいだが、店舗営業の再開後も、主に地域住民の需要に支えられて客足が絶えることはなく、逆に売上高を伸ばすことができた。ただ、原材料の高騰がA社の収益を圧迫する要因となっていた。さらに、常連である地元の顧客も高齢化し、新たな顧客層の取り込みがますます重要となっていった。

　そのような状況の中で、かつて同じ蕎麦店からのれん分けした近隣の蕎麦店X社の経営者が、自身の高齢と後継者不在のために店舗の閉鎖を検討していた。A社経営者に経営権の引き継ぎが打診されたため、2023 年より事業を譲り受けることとなった。A社の経営者は、X社との経営統合による新たな展開によって、これまで以上の売上高を期待できるという見通しを持っていた。

　X社はA社から３kmほどの距離に位置し、資本金１ 千万円、従業員12名（正社員４名、アルバイト８ 名）の体制で経営していた。店舗は50席で一見の駅利用者や通勤客をターゲットとしており、A社よりは客単価を抑えて顧客回転率を高めるオペレーションであったため、接客やサービスは省力化されてきた。原材料の調達については、X社経営者の個人的なつながりがある中堅の食品卸売業者より仕入れていた。この食品卸売業者は、地元産の高品質な原材料をも扱う生産者と直接取引をしていた。社内の従業員の業務に関しては、厨房、接客、管理の担当制がありX社経営者が定めた業務ルーティンで運営されていた。厨房、接客、管理の従業員は担当業務に専念するのみで横のつながりが少なく、淡々と日々ルーティンをこなしている状況であった。店舗レイアウトやメニューの変更などの担当を横断する意思疎通が必要な場合、X社経営者がそれを補っていた。

　10年前に駅の構内に建設された商業ビル内に、ファーストフード店やチェーン経営の蕎麦店が進出して競合するようになり、駅前に立地しながらも急速に客足が鈍くなり売上高も減少し始めていた。この頃から、X社では価格を下げて対応を始めるとともに、朝昼から深夜までの終日営業に変更した。ただ、駅構内に出店した大手外食チェーンとの価格競争は難しく、商品やサービスの差別化が必要であった。営業時間が、早朝から夜遅くまでであったことから、アルバイト従業員のシフト制を敷いて対応していたが、コロナ禍の影響でさらに来店客が減少し、営業時間を大幅に短縮し、アルバイトの数を16名から８ 名に減らしてシフト制を廃止していた。ただ、営業時間内は厨房も接客もオペレーションに忙殺されることから、仕事がきついことを理由に離職率も高く、常にアルバイトを募集する必要があった。

　近年では、地域の食べ歩きを目的とした外国人観光客や若者が増え始めた。とりわけSNSの口コミやグルメアプリを頼りに、公共交通機関を利用する来訪者が目立つようになった。X社を買収後の経営統合にともなって、不安になったX社の正社員やアルバイトから退職に関わる相談が出てきている。A社ではどのように経営統合を進めていくべきか、中小企業診断士に相談することとした。



（令和5年度　中小企業診断士2次筆記試験　事例1　問題より引用）

## 問題


### 第1 問（配点20 点）

#### 問題文

統合前のA社における①強みと②弱みについて、それぞれ30字以内で述べよ。

#### ロジック

##### 現状分析

[plantuml]
----
@startmindmap

* 強み
** 強豪との差別化につながる、商品とサービスの質の高さ。
*** 蕎麦を自前で打っており、コシの強い蕎麦が人気を博した。
*** （商品に)使用する原材料を厳選している。
*** オリジナルメニューを開発し、近隣の競合する外食店とは異なる、商品サービスの質を高めることで、差別化を行った。
** マイカーで来店しやすい県道沿いの立地。
*** 県道沿いの立地が功を奏し、マイカーで来店する顧客が増加。
** 自主的に問題を提起し、チームで助け合い解決する組織風土。
*** チームとして相互に助け合う土壌が生まれ、従業員が定着。
*** 接客において、自主的に問題を提起し解決するような風土が醸成されている。
* 弱み
** （商品とサービスの質を高めて差別化を行った)
*** 近隣にファミリーレストランなどの競合が多数現れた。
** （チームで助け合う土壌が生まれ、従業員が定着)
*** 正社員の離職が相次いでサービスの質の低下を招いた。
*** 仕事の負担が大きく、疲弊して辞めていく従業員が相次いだ。
** （オリジナルメニューを開発、接客において自主的に問題解決する風土が醸成）
*** 新規メニューの開発力が弱く、接客サービスが粗雑だった。
** 原材料の仕入が不安定、収益を圧迫している。
*** 原材料の仕入業者の高齢化によって、原材料の仕入が不安定。
*** 原材料の高騰が収益を圧迫する要因となっていた。
** 常連顧客が高齢化、新規顧客の獲得が不足。
*** 常連である地元の顧客が高齢化し、新たな顧客層の取り込みが重要。

@endmindmap
----

##### 課題設定

##### 解決策

#### 解答

### 第2 問（配点20 点）

#### 問題文

A社の現経営者は、先代経営者と比べてどのような戦略上の差別化を行ってきたか、かつその狙いは何か。100字以内で述べよ。

#### ロジック

##### 現状分析

[plantuml]
----
@startmindmap

* どのような差別化を行ったか
-- （現経営者は）経営方針を見直して、メインの客層を地元のファミリー層に絞り込んだ。家族や友人など複数で来店する顧客が増加した。
-- （商品に）使用する原材料を厳選して、以前よりも価格を引き上げた。
-- 看板となるオリジナルメニューを開発し、近隣の競合する外食店とは異なる。商品とサービスの質を高めることで、差別化を行った。
** メインの客層を地元のファミリー層に絞り込んだ。
** 原材料を厳選して、高価格商品を提供した。
** オリジナルメニューを開発し、高品質・高付加価値商品を提供した。
* 競合
** 近隣にファミリーレストランやうどんやラーメンなどのチェーン店、コンビニエンスストアなどの競合。
* 先代の方針の見直し
** 先代が行っていた総花的なメニューを見直し、元々の看板であった蕎麦に資源を集中した。
** 現経営者に引き継がれてから5年間は前年度の売上高を上回るようになり、安定的に利益を確保できる体制となった。
*** 狙い
**** 高付加価値商品を提供して客単価を上げる。
**** 売上高を拡大し、安定的に利益を確保する。

@endmindmap
----

##### 課題設定

##### 解決策

#### 解答

### 第3 問（配点20 点）　

#### 問題文

A社経営者は、経営統合に先立って、X社のどのような点に留意するべきか。100字以内で助言せよ。

#### ロジック

##### 現状分析

[plantuml]
----
@startmindmap

* 近隣の蕎麦店X社の経営者が、自身の高齢と後継者不在のために店舗の閉鎖を検討。
* A社よりは客単価を抑えて顧客回転率を高めるオペレーションで、接客やサービスを省力化。
* 原材料の調達は、X社経営者の個人的なつながりがある食品卸業者より仕入れていた。
* 従業員の業務は、X社経営者が定めたルーティーンで運営。横のつながりが少なく、担当を横断する意思疎通は、X社経営者が担う。
* チェーン店などが進出して競合するようになり、売上が減少。
* 大手外食チェーンとの価格競争は難しく、商品やサービスの差別化が必要であった。
* 営業時間内はオペレーションに忙殺されて、仕事がきついことを理由に離職率が高い。

@endmindmap
----

##### 課題設定

[plantuml]
----
@startmindmap

* 経営統合に先立って、X社のどのような点に留意するべきか

@endmindmap
----

##### 解決策

[plantuml]
----
@startmindmap

* 事業面
** 接客やサービスを省力化しているが、大手との価格競争に苦しむ。
* 組織面
** 従業員は定められたルーティーンで業務を運営。横のつながりが少ない。従業員の離職率が高い。
* X社経営者への依存、権限集中
** 担当を横断する意思疎通は、X社経営者が担う。
** 卸売業者は、X社経営者の個人的なつながりがある業者。

@endmindmap
----

#### 解答

### 第4 問（配点40 点）

A社とX社の経営統合過程のマネジメントについて、以下の設問に答えよ。

#### （設問１）

##### 問題文

どのように組織の統合を進めていくべきか。80字以内で助言せよ。

##### ロジック

###### 現状分析

[plantuml]
----
@startmindmap

* (第3問より)X社は、従業員は定められたルーティーンで業務を運営。横のつながりが少ない。従業員の離職率が高い。
* 買収後の経営統合にともなって、不安になったX社の従業員から退職に関わる相談が出てきている。
* （第1問より）A社は、自主的に問題を解決する、相互に助け合う組織風土。従業員が定着。
* 経営者の下に接客、厨房、管理の３部体制とし、それぞれに専業できるリーダーを配置括。
* 接客リーダーは、全体を統括する役割を担い、将来は自分の店を持ちたいと思っていた。
* A社経営者は、接客リーダーとともに会社として目指す方向性を明確にし、目的意識の共有や意思の統一を図るチームづくりを行った。

@endmindmap
----

###### 課題設定

[plantuml]
----
@startmindmap

* X社従業員の不安を解消する。
* A社のような自主的に行動し、相互に助け合う組織風土を醸成する。

@endmindmap
----

###### 解決策

[plantuml]
----
@startmindmap

* 会社の目指す方向性を説明し、X社従業員の不安を解消する。
* A社の接客リーダーがX社全体を統括する役割を担う。

@endmindmap
----

##### 解答

#### （設問２）

##### 問題文

今後、どのような事業を展開していくべきか。競争戦略や成長戦略の観点から100字以内で助言せよ。

##### ロジック

###### 現状分析

[plantuml]
----
@startmindmap

* （第1問より）A社の強みは、商品とサービスの質の高さ。
* （第1問より）A社の弱みは、新規顧客の獲得不足、原材料仕入れの不安定さ。
* （第2問より）A社はオリジナルメニューを開発、高付加価値商品を提供し、差別化を行った。
* （第3問より）X社は価格競争に苦しんでいる。
* X社が仕入れている食品卸業者は、地元産の高品質な原材料を扱い生産者と直接取引。
* 地域の食べ歩きを目的として外国人観光客や若者が増え始めた。SNSの口コミやグルメアプリを頼りに、公共交通機関を利用する来訪者が目立つ。
* 駅の構内に競合店が進出して、（Ⅹ社は）駅前に立地しながらも急速に客足が鈍くなった。

@endmindmap
----

###### 課題設定

[plantuml]
----
@startmindmap

* 競争戦略や成長戦略の観点から、どのような事業を展開していくべきか

@endmindmap
----

###### 解決策

[plantuml]
----
@startmindmap

* 競争戦略
** A社は、オリジナルメニューを開発して差別化。
** X社は、地元産の高品質な原材料を扱う卸売業者と取引。
* 成長戦略
** A社は、新規顧客の獲得が不足している。
** X社は、近隣に競合店が進出して、客足が鈍っている。
** 地域では、外国人環境客や若者が増加。
*** 食べ歩きを目的とした外国人環境客や若者向けの商品を販売し、成長を目指す。

@endmindmap
----

##### 解答
