# B社の事例

## 与件文

　B社は資本金3,000 万円、従業者数は45 名（うちパート従業員21 名）で、食肉と食肉加工品の製造・販売を行う事業者である。現在の事業所は本社、工場、直営小売店1 店舗である。2021 年度の販売額は約9 億円で、取扱商品は牛肉・豚肉・鶏肉・食肉加工品である。

　B社はX県の大都市近郊に立地する。高速道路のインターチェンジからも近く、車の利便性は良いエリアだ。B 社の周辺には、大規模な田畑を所有する古くからの住民もいるが、工業団地があるため、現役世代が家族で居住する集合住宅も多い。

　1955年、B 社はこの地で牛肉、豚肉、鶏肉、肉の端材を使った揚げたてコロッケなどの総菜を販売する食肉小売店を開業した。当時の食肉消費拡大の波に乗って順調に売り上げを伸ばしたB 社は、1960 年代に入ると、食肉小売事業に加え、地域の百貨店や近隣のスーパーなどの大型小売業へ食肉を納入する事業を手がけるようになった。

　百貨店やスーパーを取引先としてきたこともあって、B 社の商品はクオリティの高さに定評がある。仕入れ元からのB 社に対する信頼も厚く、良い食肉を仕入れられる体制が整っている。B 社は、百貨店向けには贈答用を含めた最高級品質の食肉や食肉加工品の販売を行い、直営の食肉小売店では対面接客による買物客のニーズに合わせた販売を行い、スーパー向けには食卓で日常使いしやすいカット肉やスライス肉などの販売を行っており、さまざまな食肉の消費機会に対応できる事業者である。

　大型小売業の成長とともにB 社も成長していたが、1980 年代後半以降、スーパーは大手食肉卸売業者と取引を行うようになったため、B 社からスーパーへの納入量は徐々に減少していった。現在、B 社の周囲5 km 圏内には広大な駐車場を構える全国チェーンのスーパーが3 店舗あり、食肉も取り扱っているが、いずれもB 社との取引関係はない。

　こうした経営環境の変化を前に、B 社社長は、直営の食肉小売店での販売と百貨店やスーパーを主要取引先とする商売を続けていくことに危機を感じた。そこで1990年代に入ってすぐ、次に挙げる3 点で事業内容の見直しを行った。

　第1に、新たな取引先の開拓である。従来の百貨店やスーパーとの取引に加え、県内や隣接県のホテル・旅館、飲食店などに活路を見出した。B 社のあるX 県は、都市部と自然豊かな場所がともに存在し、高速道路で行き来できる。また、野菜・果物・畜産などの農業、漁業、機械や食品などの工業、大型ショッピングセンターなどの商業、観光サービス業がバランスよく発展している。山の幸、海の幸の特産品にも恵まれ、大規模な集客施設もあれば、四季それぞれに見どころのある観光エリアもあり、新たな取引先探しには事欠かなかった。

　第2に、自社工場を新設し、食肉加工品製造も行えるようにした。高い技術力を有する職人をB 社に招き入れ、良質でおいしい食肉加工品を製造できる体制を整えた。これによって、B 社は最高級のハムやソーセージ、ローストビーフなどの食肉加工品を自社ブランドで開発できるようになった。単品販売もできるうえ、詰め合わせれば贈答品にもなり、これら食肉加工品は直営小売店や高速道路の土産物店、道の駅などで販売している。また、取引先のニーズに応じて、相手先ブランドでの食肉加工品製造を請け負うことも可能になった。

　これと関連して第3 に、取引先へのコンサルテーションも手がけるようになった。自社工場設立以前、B 社は食肉販売を主な事業としていたため、取り扱う商品は標準的なカットやスライスを施した食肉であり、高度な加工を必要としなかった。しかし、ホテル・旅館や飲食店との取引の場合、販売先の調理の都合に合わせた形状のカットや、指定された個数でのパッキング、途中工程までの調理済み商品が求められるなど、顧客ニーズにきめ細かく合わせることが必要となってきた。B 社は自社工場という加工の場をもつことによって、個々の顧客の要望に応じた納品が可能になった。最近では、飲食店に対してメニュー提案を行ったり、その半加工を請け負ったりすることも増えている。

　事業見直しを進めた現在、B 社取引先の多くは1990 年代以降に開拓した事業者となった。2019 年度時点でのB 社の売上構成比は、卸売事業が9 割、直営小売事業が1 割である。折からのインバウンド需要の拡大を受け、ホテル・旅館との取引は絶好調であった。加えて2020 年夏には東京オリンピック・パラリンピックを控え、B 社はさらなる飛躍を期待し、冷凍在庫も積み増していた。

　ところが、国内での新型コロナウイルス感染症の発生を受け、ホテル・旅館や飲食店などを主要取引先とするB 社の経営は大打撃を受けた。B 社の2020 年度の売り上げは、2019 年度のおよそ半分となった。2021 年度の売り上げも2020 年度から多少回復がみられる程度だ。東京オリンピック・パラリンピックのために積み増した冷凍在庫をさばくため、B 社は大手ネットショッピングモールに出店し、焼肉用やステーキ用として冷凍肉の販売も試してみた。しかし、コロナ禍で同じことを考えた食肉販売業者は多く、B 社紹介ページはネット上で埋もれ、消費者の目にはほとんど留まらないようだった。B 社にとってせめてもの救いは、直営の食肉小売店であった。コロナ禍の巣ごもり需要拡大の影響で、開業以来、とくに何の手も打って来なかった食肉小売店での販売だけが急上昇した。料理の楽しさに目覚めた客や、作りたての揚げ物を買い求める客が、食肉専門店の魅力に気づいて足を運ぶようになった結果だった。

　B社社長はこの2年以上、コロナ禍で長期にわたって取引が激減しているホテル・旅館や、続々と閉店する飲食店を目の当たりにしてきた。もちろんB 社の販売先の多くはまだ残っているが、コロナ収束後、これらの事業者がすぐにコロナ前の水準で取引してくれるようになるとはとても思えずにいる。

　B社社長は高齢のため、同社専務を務める息子がまもなく事業を承継する予定だ。アフターコロナと事業承継を見据え、B 社社長は自社事業の再構築を行うべく、中小企業診断士に相談した。B 社はこのところ卸売事業を主軸としてきた。しかし、中小企業診断士との対話を重ねていくうち、B 社社長は自社の売り上げが他社の動向に左右されていることに気づき、今後はB 社自身が最終消費者と直接結びつく事業領域を強化すべきであると納得するに至った。B 社社長は、自社の強みを生かした新たな事業展開ができるよう、中小企業診断士にさらなる助言を求めた。

（令和4年度　中小企業診断士2次筆記試験　事例2　問題より引用）

## 問題

### 第1問（配点20 点）

#### 問題文

B社の現状について、3C（Customer：顧客、Competitor：競合、Company：自社）分析の観点から150 字以内で述べよ。

#### ロジック

##### 現状分析

[plantuml]
----
@startmindmap

* 顧客
** 2019年度時点のB社の売上構成比は、卸売事業が9割、直営事業が1割である。
** 卸売事業
*** 卸売事業では、百貨店やスーパー、ホテル・旅館、飲食店などが顧客。
**** 百貨店向けに贈答用を含めた食肉や食肉加工品の販売を行い、スーパー向けにはカット肉やスライス肉などの販売を行う。
**** 従来の百貨店やスーパーとの取引に加えて、県内や隣接県のホテル・旅館、飲食店などに活路を見出した。
**** 食肉加工品は高速道路の土産物店、道の駅などでも販売。
** 直営小売事業
*** 食肉小売店では、B社周辺の古くからの住民や集合住宅の家族などが顧客。
*** 直営の食肉小売店では対面接客による買物客のニーズに合わせた販売。
*** B社の周辺には、大規模な田畑を所有する古くからの住民もいるが、現役世代が家族で居住する集合住宅も多い。
* 競合
** スーパーへの卸売では、大手食肉卸売業者が競合。
*** スーパーは大手食肉卸事業者と取引を行うようになったため、B社からスーパーへの納入量は徐々に減少。
** ネット販売を行う食肉販売業者が競合。
*** ネットショッピングモールに出店し、冷凍肉の販売も試みたが、コロナ禍で同じことを考えた食肉販売業者は多く、B社紹介ページはネット上で埋もれた。
* 自社
** コロナ禍により、卸売事業は売上が大きく減少した。
*** 新型コロナウィルス感染症の発生を受け、ホテル・旅館や飲食店などを主取引先とするB社の経営は大打撃を受けた。
** 巣ごもり需要拡大により、食肉小売店の販売は急上昇した。
*** コロナ禍の巣ごもり需要拡大の影響で、直営の食肉小売店での販売は急上昇した。
** 良質な食肉を仕入れて、高品質の商品を提供している。
*** B社の商品はクオリティの高さに定評がある。
*** 仕入元からの信頼も厚く、良い食肉を仕入れられる体制が整っている。

@endmindmap
----

#### 解答


### 第2問（配点20 点）

#### 問題文

B社は、X県から「地元事業者と協業し、第一次産業を再活性化させ、県の社会経済活動の促進に力を貸してほしい」という依頼を受け、B社の製造加工技術力を生かして新たな商品開発を行うことにした。商品コンセプトと販路を明確にして、100 字以内で助言せよ。

#### ロジック

##### 現状分析

[plantuml]
----
@startmindmap

* 地元事業、第一次産業
** X県は、野菜・果物・畜産などの農業、漁業、工業、商業、観光サービス業がバランスよく発展。
** 山の幸、海の幸の特産品に恵まれ、大規模な集客施設や見どころのある観光エリアもある。
* B社の製造加工技術
** 高い技術力を有する職人がおり、良質でおいしい食肉加工品を自社ブランで開発。
** 相手先ブランドでの食肉加工製造を請け負うことも可能。
* 販路
** X県には、大型ショッピングセンターや大規模な集客施設がある。
** B社は、地域の百貨店やスーパー、ホテル・旅館、飲食店などに卸売りをしている。
** ホテル・旅館、飲食店などは、新型コロナウィルス感染症の発生の影響を大きく受けている。
** 食肉加工品は高速道の土産物店、道の駅などでも販売。

@endmindmap
----

##### 課題設定

[plantuml]
----
@startmindmap

* B社の製造加工技術力を生かした新たな商品開発

@endmindmap
----

##### 解決策

[plantuml]
----
@startmindmap

* 商品コンセプト
** X県産の特産品を用いた、地域ブランドの加工食品。
*** X県産の野菜・果物・畜産、山の幸・海の幸などの特産品を用いる。
*** B社は高い食肉加工技術を有し、相手ブランでの製造の請負も可能。
* 販路
** X県産の特産品を用いた高品質の地域ブランの加工食品の販売。
** 主に贈答用や観光客向け。
*** 地域の百貨店、大型商業施設にて販売。
*** 観光エリアのホテル・旅館、土産物店などで販売。

@endmindmap
----

#### 解答


### 第3問（配点20 点）

#### 問題文

アフターコロナを見据えて、B社は直営の食肉小売店の販売力強化を図りたいと考えている。どのような施策をとればよいか、顧客ターゲットと品揃えの観点から100字以内で助言せよ。

#### ロジック

##### 現状分析

[plantuml]
----
@startmindmap

* B社は牛肉、豚肉、鶏肉、肉の端材を使った揚げたてコロッケなどの総裁を販売する食肉小売店を開業した。
* コロナ禍の巣ごもり需要拡大の影響で、食肉小売店での販売が急上昇した。
* 顧客
** 料理の楽しさに目覚めた客や、作りたての揚げ物を買い求める客が、食肉専門店の魅力に気づいて足を運ぶようになった。
** B社の周辺には、大規模な田畑を所有する古くからの住民もいるが、現役世代が家族で居住する集合住宅も多い。
** 直営の食肉小売店では対面接客による買物客のニーズに合わせた販売。
* 商品
** 自社工場にて、良質でおいしい食肉加工品を製造できる。
** (自社工場設立後は)販売先の調理の都合に合わせた形状のカットや、指定された個数でのパッキング、半加工品など顧客の要望に応じた納品が可能になった。

@endmindmap
----

##### 課題設定

[plantuml]
----
@startmindmap

* アフターコロナを見据えた、直営の食肉小売店の販売力強化

@endmindmap
----

##### 解決策

[plantuml]
----
@startmindmap

* 顧客ターゲット
** 料理の楽しさに目覚めた客や、作りたての揚げ物を買い求める顧客を維持・増加させる。
*** B社周辺の現役世代の家族をターゲットとする。
* 品揃え
** 食肉
*** 自社工場にて、要望に合わせた形状のカット、個数でのパッキング、半加工品の製造ができる。
**** 料理の楽しみに関するニーズを収集し、それに合わせた食肉や半加工品を揃える。
** 惣菜
*** 食肉小売店では、食肉を使った揚げたての惣菜を販売している。
**** 作りて手の揚げ物のニーズを収集し、それに合わせて揚げたての惣菜の品揃えを拡充する。


@endmindmap
----

#### 解答

### 第4問（配点40 点）

#### 問題文

B 社社長は、新規事業として、最終消費者へのオンライン販売チャネル開拓に乗り出すつもりである。ただし、コロナ禍で試した大手ネットショッピングモールでの自社単独の食肉販売がうまくいかなかった経験から、オンライン販売事業者との協業によって行うことを考えている。

中小企業診断士に相談したところ、B 社社長は日本政策金融公庫『消費者動向調査』（令和4 年1 月）を示された。これによると、家庭での食に関する家事で最も簡便化したい工程は「献立の考案」（29.4 ％）、「調理」（19.8 ％）、「後片付け」（18.2 ％）、「食材の購入」（10.7 ％）、「容器等のごみの処分」（8.5 ％）、「盛り付け・配膳」（3.3 ％）、「特にない」（10.3 ％）とのことであった。

B社はどのようなオンライン販売事業者と協業すべきか、また、この際、協業が長期的に成功するためにB社はどのような提案を行うべきか、150 字以内で助言せよ。

#### ロジック

##### 現状分析

[plantuml]
----
@startmindmap

* 自社の売り上げが他社の動向に左右されていることに気づき、B社自信が最終消費者と直接結びつく事業領域を強化する。
* B社社長は、自社の強みを生かした新たな事業展開ができるよう助言を求めた。
* 大手ネットショッピングモールでの販売
** 大手ネットショッピングモールに出店し、焼肉用やステーキ用として冷凍肉の販売を試みたが、同じことを考えた食肉販売事業者は多く、B社の紹介ページは埋もれた。
* 消費者のニーズ
** 家事で簡便化したい工程として、「献立の考案」、「調理」、「後片付け」、「食材の購入」などが多く挙げられている。
* 献立の考案
** 飲食店に対してメニューの提案を行ったり、その半加工を請け負ったりすることも増えている。
* 調理
** 自社工場にて、高い技術力を生かし、良質でおいしい食肉加工品を製造できる。最高級のハムやソーセージ、ローストビーフなどの食肉加工品を開発できる。
* 食材
** B社は、良質な食肉を仕入れて、高品質の商品を提供している。

@endmindmap
----

##### 課題設定

[plantuml]
----
@startmindmap

* 最終消費者へのオンライン販売チャネル開拓にあたって、どのようなオンライン販売業者と協業すべきか。
* 協業が長期的に成功するためにどのような提案を行うべきか。

@endmindmap
----

##### 解決策

[plantuml]
----
@startmindmap

* B社は高品質の食肉や加工品を提供している。
** 消費者向けに低価格で手頃な食材を提供しているオンライン販売事業者ではなく、こだわりの食材を提供している販売事業者と協業する。
* 献立の考案
** B社は飲食店に対してメニュー提案をしている。
*** B社の食肉やオンライン販売事業者が扱う食材を用いたレシピを作成する。
* 調理
** B社は高い技術力を活かして、食肉加工品や半加工品を製造できる。
*** 調理しやすい高品質な半加工品を開発・提供する。
* 長期的な協業の成功
** 顧客のニーズの変化などに合わせて、継続的な見直しを行う。

@endmindmap
----

